version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "forum"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
    ports:
      - "5432:5432"
